In [1]:
import numpy as np
import tensorflow as tf

def extended_transmon_hamiltonian(EJ11, EJ12, E11, E12, n_cut, Phi, n_g, N, M, coef12=1000):
    # Define the size of the Hamiltonian
    dim = 2 * n_cut + 1
    H = np.zeros((dim, dim), dtype=complex)

    # Populate the diagonal with charging energy terms
    for n in range(-n_cut, n_cut + 1):
        index = n + n_cut
        H[index, index] = E11 * (n - n_g)**2  # Including n_g for the charge basis
    
    # Populate the diagonal with charging energy terms
    for n in range(-n_cut, n_cut + 1):
        index = n + n_cut
        H[index, index] += E12 * coef12 * (n - n_g)


    flux_term = np.exp(2j * np.pi * Phi / N)
    # Populate the off-diagonal with Josephson energy terms for the N * EJ_N * cos(M * phi) term
    for n in range(-n_cut, n_cut - M + 1):
        index = n + n_cut
        H[index, index + M] += -N * EJ11 / 2 * ( flux_term)  # Corresponding to cos(M * phi)
        H[index + M, index] += -N * EJ11 / 2 * (np.conj(flux_term))

    # Populate the off-diagonal with Josephson energy terms for the M * EJ_M * cos(N * phi + 2*pi*Phi/M) term
    for n in range(-n_cut, n_cut - N + 1):
        index = n + n_cut
        H[index, index + N] += -M *coef12* EJ12 / 2   # Corresponding to cos(N * phi + 2*pi*Phi/M)
        H[index + N, index] += -M *coef12* EJ12 / 2 

    return H.real  # Return the Hermitian part


H1 = extended_transmon_hamiltonian(EJ11=1.8, EJ12=18, E11=125.174717, E12=-249.650567, n_cut=1, Phi=0, n_g=0, N=1, M=1, coef12=0)
print(np.round(H1, 2)) 
# Solve eigenvalue problem
eigenvalues_1, eigenvectors_1 = tf.linalg.eigh(H1)
# Convert to numpy for inspection (if needed)
eigenvalues_1 = eigenvalues_1.numpy()
print(sorted(eigenvalues_1))


[[125.17  -0.9    0.  ]
 [ -0.9    0.    -0.9 ]
 [  0.    -0.9  125.17]]
Metal device set to: Apple M2 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

[-0.012940572828096594, 125.17471699999997, 125.18765757282804]


2024-11-27 09:47:40.433497: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-27 09:47:40.433647: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [97]:
125.17471699999997 - 0.012940572828096594

125.16177642717187

In [37]:
eigenvectors_1[:, 0]

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-0.00718884, -0.99994832, -0.00718884])>

In [98]:
import numpy as np
import tensorflow as tf

def extended_transmon_hamiltonian(EJ11, EJ12, E11, E12, n_cut, Phi, n_g, N, M, coef12=1000):
    # Define the size of the Hamiltonian
    dim = 2 * n_cut + 1
    H = np.zeros((dim, dim), dtype=complex)

    # Populate the diagonal with charging energy terms
    for n in range(-n_cut, n_cut + 1):
        index = n + n_cut
        H[index, index] = E11 * (n - n_g)**2  # Including n_g for the charge basis
    
    # Populate the diagonal with charging energy terms
    for n in range(-n_cut, n_cut + 1):
        index = n + n_cut
        H[index, index] += E12 * coef12 * (n - n_g)


    flux_term = np.exp(2j * np.pi * Phi / N)
    # Populate the off-diagonal with Josephson energy terms for the N * EJ_N * cos(M * phi) term
    for n in range(-n_cut, n_cut - M + 1):
        index = n + n_cut
        H[index, index + M] += -N * EJ11 / 2 * ( flux_term)  # Corresponding to cos(M * phi)
        H[index + M, index] += -N * EJ11 / 2 * (np.conj(flux_term))

    # # Populate the off-diagonal with Josephson energy terms for the M * EJ_M * cos(N * phi + 2*pi*Phi/M) term
    # for n in range(-n_cut, n_cut - N + 1):
    #     index = n + n_cut
    #     H[index, index + N] += -M *coef12* EJ12 / 2   # Corresponding to cos(N * phi + 2*pi*Phi/M)
    #     H[index + N, index] += -M *coef12* EJ12 / 2 

    return H.real  # Return the Hermitian part


H2 = extended_transmon_hamiltonian(EJ11=1.8, EJ12=18, E11=125.174717, E12=-249.650567, n_cut=1, Phi=0, n_g=0, N=1, M=1, coef12=+1)
print(np.round(H2, 2)) 
# Solve eigenvalue problem
eigenvalues_2, eigenvectors_2 = tf.linalg.eigh(H2)
# Convert to numpy for inspection (if needed)
eigenvalues_2 = eigenvalues_2.numpy()
print(sorted(eigenvalues_2))


[[ 374.83   -0.9     0.  ]
 [  -0.9     0.     -0.9 ]
 [   0.     -0.9  -124.48]]
[-124.48235703099883, 0.004346027271620665, 374.8274450037272]


In [78]:
for j in range(H2.shape[0]):
    print(eigenvectors_2[:, j])

tf.Tensor([-9.99973864e-01 -7.22984548e-03 -1.30317672e-05], shape=(3,), dtype=float64)
tf.Tensor([-0.00722986  0.99997098  0.00240108], shape=(3,), dtype=float64)
tf.Tensor([-4.32802571e-06  2.40110833e-03 -9.99997117e-01], shape=(3,), dtype=float64)


In [23]:
import numpy as np

def construct_hamiltonian(n_cut, Phi_1=0.0, n_g1=0.0, n_g2=0.0):
    # Define the basis states
    basis = []
    for n1 in range(-n_cut, n_cut + 1):
        for n2 in range(-n_cut, n_cut + 1):
            basis.append((n1, n2))
    
    # Map basis states to indices
    n1n2_to_index = { (n1, n2): idx for idx, (n1, n2) in enumerate(basis) }
    
    # Initialize the Hamiltonian matrix
    dim = len(basis)
    H = np.zeros((dim, dim), dtype=complex)
    
    # Constants from the Hamiltonian
    E_n1_n1 = 125.174717 # TODO precision?
    E_n1_n2 = -249.650567
    E_n1_ng1 = 250.349433
    E_n1_ng2 = -249.650567
    E_n2_n2 = 125.174717
    E_n2_ng1 = -249.650567
    E_n2_ng2 = 250.349433
    E_ng1_ng1 = 125.174717
    E_ng1_ng2 = -249.650567
    E_ng2_ng2 = 125.174717
    
    # Charging energy terms (diagonal)
    for idx, (n1, n2) in enumerate(basis):
        H_c = (
            E_n1_n1 * (n1 - n_g1)**2 +
            E_n2_n2 * (n2 - n_g2)**2 +
            E_n1_n2 * (n1 - n_g1) * (n2 - n_g2)
        )
        print("idx", idx, 'value', (n1 - n_g1))
        H[idx, idx] = H_c
    
    # Potential energy terms (off-diagonal)
    # V1: -1.8 * cos(θ1)
    for idx, (n1, n2) in enumerate(basis):
        coeff = -0.9  # -1.8 / 2
        for delta_n1 in [-1, 1]:
            n1p = n1 + delta_n1
            n2p = n2
            if -n_cut <= n1p <= n_cut:
                idxp = n1n2_to_index.get((n1p, n2p))
                if idxp is not None:
                    H[idx, idxp] += coeff
    
    # V2: -1.8 * cos((2πΦ_1) - θ2)
    phi = 2 * np.pi * Phi_1
    exp_plus = np.exp(-1j * phi)
    exp_minus = np.exp(1j * phi)
    for idx, (n1, n2) in enumerate(basis):
        coeff = -0.9
        # First term: n2 -> n2 + 1
        n1p = n1
        n2p = n2 + 1
        if -n_cut <= n2p <= n_cut:
            idxp = n1n2_to_index.get((n1p, n2p))
            if idxp is not None:
                H[idx, idxp] += coeff * exp_plus
        # Second term: n2 -> n2 - 1
        n2p = n2 - 1
        if -n_cut <= n2p <= n_cut:
            idxp = n1n2_to_index.get((n1p, n2p))
            if idxp is not None:
                H[idx, idxp] += coeff * exp_minus
    
    # # V3: -18.0 * cos(θ1 + θ2)
    for idx, (n1, n2) in enumerate(basis):
        coeff = -9  # -18.0 / 2
        # First term: n1 -> n1 + 1, n2 -> n2 + 1
        n1p = n1 + 1
        n2p = n2 + 1
        if -n_cut <= n1p <= n_cut and -n_cut <= n2p <= n_cut:
            idxp = n1n2_to_index.get((n1p, n2p))
            if idxp is not None:
                H[idx, idxp] += coeff
        # Second term: n1 -> n1 - 1, n2 -> n2 - 1
        n1p = n1 - 1
        n2p = n2 - 1
        if -n_cut <= n1p <= n_cut and -n_cut <= n2p <= n_cut:
            idxp = n1n2_to_index.get((n1p, n2p))
            if idxp is not None:
                H[idx, idxp] += coeff
    
    # Ensure the Hamiltonian is Hermitian
    H = (H + H.conj().T) / 2
    return H.real  # Return the real part

# Example usage
n_cut = 1  # Charge basis cutoff
Phi_1 = 0.0  # External flux Φ_1 in units of Φ/Φ0
n_g1 = 0.0  # Offset charge n_g1
n_g2 = 0.0  # Offset charge n_g2

hamiltonian_matrix = construct_hamiltonian(n_cut, Phi_1, n_g1, n_g2)
print(np.round(hamiltonian_matrix, 2))

# Solve eigenvalue problem
eigenvalues, eigenvectors = np.linalg.eigh(hamiltonian_matrix)
print("Eigenvalues:", sorted(eigenvalues))

# Compute the ratio as requested
max_diag = np.max(np.diag(hamiltonian_matrix))
size = hamiltonian_matrix.shape[0]
off_diag_element = hamiltonian_matrix[0, 1]
ratio = max_diag / size**2 / off_diag_element
print("Computed Ratio:", ratio)


idx 0 value -1.0
idx 1 value -1.0
idx 2 value -1.0
idx 3 value 0.0
idx 4 value 0.0
idx 5 value 0.0
idx 6 value 1.0
idx 7 value 1.0
idx 8 value 1.0
[[  0.7   -0.9    0.    -0.9   -9.     0.     0.     0.     0.  ]
 [ -0.9  125.17  -0.9    0.    -0.9   -9.     0.     0.     0.  ]
 [  0.    -0.9  500.     0.     0.    -0.9    0.     0.     0.  ]
 [ -0.9    0.     0.   125.17  -0.9    0.    -0.9   -9.     0.  ]
 [ -9.    -0.9    0.    -0.9    0.    -0.9    0.    -0.9   -9.  ]
 [  0.    -9.    -0.9    0.    -0.9  125.17   0.     0.    -0.9 ]
 [  0.     0.     0.    -0.9    0.     0.   500.    -0.9    0.  ]
 [  0.     0.     0.    -9.    -0.9    0.    -0.9  125.17  -0.9 ]
 [  0.     0.     0.     0.    -9.    -0.9    0.    -0.9    0.7 ]]
Eigenvalues: [-12.420165123968943, 0.6867310763901656, 13.0810125847379, 116.17049637604966, 116.20851581084952, 134.17471700000004, 134.18685292360993, 500.00422162395023, 500.00422172838154]
Computed Ratio: -6.858710576131687


In [22]:
-0.02634917330212343 - 12.723, 0.6863288740906414 + 12.723

(-12.749349173302123, 13.409328874090642)

In [13]:
subdiag_m5 = np.diag(hamiltonian_matrix, k=-4)
subdiag_5 = np.diag(hamiltonian_matrix, k=4)
V = np.diag(subdiag_m5, k=-4) + np.diag(subdiag_5, k=4)
# V

In [24]:
import numpy as np

def perturbation_energy_corrections(H0, V, max_order=4):
    """
    Compute perturbative energy corrections up to the specified order.

    Parameters:
    H0 (ndarray): Unperturbed Hamiltonian (NxN matrix).
    V (ndarray): Perturbation Hamiltonian (NxN matrix).
    max_order (int): Maximum order of corrections to compute (default is 4).

    Returns:
    dict: Dictionary where keys are state indices and values are lists of energy corrections.
    """
    # Diagonalize the unperturbed Hamiltonian
    E0, psi0 = np.linalg.eigh(H0)
    psi0_dag = np.conjugate(psi0).T

    # Transform V into the eigenbasis of H0
    V_tilde = psi0_dag @ V @ psi0

    print(np.round(V_tilde,2))

    # Number of states
    N = len(E0)

    # Initialize dictionary to store energy corrections
    energy_corrections = {n: [0] * (max_order + 1) for n in range(N)}

    # Compute first-order corrections
    for n in range(N):
        energy_corrections[n][1] = V_tilde[n, n].real

    # Compute second-order corrections
    for n in range(N):
        sum_term = 0
        for k in range(N):
            if k != n:
                sum_term += (abs(V_tilde[k, n])**2) / (E0[n] - E0[k])
        energy_corrections[n][2] = sum_term.real

    # Compute third-order corrections
    for n in range(N):
        sum_term1 = 0
        sum_term2 = 0
        for k in range(N):
            if k != n:
                for m in range(N):
                    if m != n:
                        sum_term1 += (V_tilde[n, m] * V_tilde[m, k] * V_tilde[k, n]) / ((E0[n] - E0[m]) * (E0[n] - E0[k]))
                sum_term2 += (abs(V_tilde[n, k])**2 * V_tilde[k, k]) / ((E0[n] - E0[k])**2)
        energy_corrections[n][3] = (sum_term1 - sum_term2).real

    # Fourth-order corrections are more complex and are not included in this implementation

    return energy_corrections


corrections = perturbation_energy_corrections(hamiltonian_matrix-V, V)

# Display corrections
for state, corr in corrections.items():
    print(f"State {state}:")
    for order, value in enumerate(corr):
        print(f"  Order {order}: {value}")


[[ -0.66  -0.   -12.71   0.    -0.     0.    -0.     0.     0.  ]
 [ -0.     0.     0.     0.     0.     0.09  -0.    -0.     0.  ]
 [-12.71   0.     0.66  -0.    -0.    -0.    -0.09   0.     0.  ]
 [  0.     0.    -0.    -9.     0.     0.     0.    -0.03  -0.  ]
 [ -0.     0.    -0.     0.     9.    -0.    -0.     0.    -0.  ]
 [  0.     0.09  -0.     0.    -0.     9.     0.     0.     0.  ]
 [ -0.    -0.    -0.09   0.    -0.     0.    -9.     0.    -0.03]
 [  0.    -0.     0.    -0.03   0.     0.     0.    -0.     0.  ]
 [  0.     0.     0.    -0.    -0.     0.    -0.03   0.    -0.  ]]
State 0:
  Order 0: 0
  Order 1: -0.6553469385802378
  Order 2: -226.68464323753804
  Order 3: -7.930425613267289e-05
  Order 4: 0
State 1:
  Order 0: 0
  Order 1: 0.0009406999607725013
  Order 2: -6.79942742523265e-05
  Order 3: -5.102306245693619e-15
  Order 4: 0
State 2:
  Order 0: 0
  Order 1: 0.6562870680697438
  Order 2: 226.68457679651712
  Order 3: 7.975813477401061e-05
  Order 4: 0
State 3:
  

In [89]:

for i in range(H1.shape[0]):
    for j in range(H2.shape[0]):
        eigenvec_tens = np.kron(eigenvectors_1[:, i], eigenvectors_2[:, j])
        print("vec", i, j, eigenvec_tens.T @(hamiltonian_matrix @ eigenvec_tens))


'''
### for 0:
vec 0 0       -0.025881145656193184
vec 0 1 / 1 0 125.16177642717192
vec 2 0 / 0 2 125.174717

### for -1: (upper 3x3)

'''

vec 0 0 125.14221991005512
vec 0 1 0.003015615498086098
vec 0 2 125.16537675596248
vec 1 0 250.32987748126246
vec 1 1 125.19067318832609
vec 1 2 250.35303433041142
vec 2 0 250.342818057332
vec 2 1 125.2036137611543
vec 2 2 250.36597489999778


'\n### for 0:\nvec 0 0       -0.025881145656193184\nvec 0 1 / 1 0 125.16177642717192\nvec 2 0 / 0 2 125.174717\n\n### for -1: (upper 3x3)\n\n'

In [33]:
a = np.zeros_like(H1)
a[0][0] = 100
# a[-1][-1] = 100

for i in range(H1.shape[0]):
    print(f"EVEC {i}")
    print(np.linalg.eigh(H1)[1][:,i])
    print(np.linalg.eigh(H1+a)[1][:,i])
    continue

orig_eval, orig_evec = np.linalg.eigh(H1)
repl_eval, repl_evec = np.linalg.eigh(H1+a)
# print("orig_eval", orig_eval)
# print("repl_eval", repl_eval)

# print((orig_evec[:,0] + orig_evec[:, 1])/np.sqrt(2))
# print(repl_evec[:, 0])


EVEC 0
[-1.03228081e-08 -1.29216943e-05 -7.18892846e-03 -9.99948318e-01
 -7.18892846e-03 -1.29216943e-05 -1.03228081e-08]
[-9.48121797e-09 -1.29216927e-05 -7.18892846e-03 -9.99948318e-01
 -7.18892846e-03 -1.29216943e-05 -1.03228081e-08]
EVEC 1
[-1.52307679e-06 -1.69467660e-03 -7.07104750e-01 -5.43230069e-14
  7.07104750e-01  1.69467660e-03  1.52307679e-06]
[ 1.38479096e-06  1.69467624e-03  7.07104739e-01  1.65703687e-10
 -7.07104762e-01 -1.69467663e-03 -1.52307682e-06]
EVEC 2
[ 1.52307024e-06  1.69464741e-03  7.07068206e-01 -1.01666947e-02
  7.07068206e-01  1.69464741e-03  1.52307024e-06]
[ 1.38478343e-06  1.69464711e-03  7.07068217e-01 -1.01666947e-02
  7.07068194e-01  1.69464738e-03  1.52307022e-06]
EVEC 3
[ 1.01680388e-03  7.07099791e-01 -1.69466690e-03 -3.64318692e-11
  1.69468717e-03 -7.07108248e-01 -1.01681604e-03]
[-6.46190392e-08 -5.21168866e-05  1.14581564e-07  4.30772728e-06
 -2.39664557e-03  9.99996093e-01  1.43798643e-03]
EVEC 4
[ 1.01681604e-03  7.07108248e-01 -1.69470177e

In [5]:
import numpy as np
import sympy
from sympy import cos, pi, symbols, sqrt
from sympy.physics.quantum import Operator
from pymablock import block_diagonalize

# Define the symbols
ng1, ng2, Phi1 = symbols('n_g1 n_g2 Phi_1', real=True)
n1, n2 = symbols('n1 n2', integer=True)
theta1, theta2 = symbols('theta1 theta2', real=True)

# Define operators
N1 = Operator('N1')
N2 = Operator('N2')
Theta1 = Operator('Theta1')
Theta2 = Operator('Theta2')

# Define the Hamiltonian terms
H_charge = (
    125.174717*N1**2 + 125.174717*N2**2 + 125.174717*ng1**2 + 125.174717*ng2**2
    + 250.349433*N1*ng1 + 250.349433*N2*ng2 - 249.650567*N1*N2 - 249.650567*N1*ng2
    - 249.650567*N2*ng1 - 249.650567*ng1*ng2
)

H_josephson = (
    -18.0*cos(Theta1 + Theta2) - 1.8*cos(Theta1) - 1.8*cos(2*pi*Phi1 - Theta2)
)

H = H_charge + H_josephson

# Define the basis states
N_max = 5  # Truncation parameter
n_values = range(-N_max, N_max + 1)
basis_states = [(n1_val, n2_val) for n1_val in n_values for n2_val in n_values]

# Map basis states to indices
state_indices = {state: idx for idx, state in enumerate(basis_states)}
dim = len(basis_states)
H_matrix = sympy.Matrix(np.zeros((dim, dim)))

# Compute the Hamiltonian matrix elements
for (n1_i, n2_i) in basis_states:
    idx_i = state_indices[(n1_i, n2_i)]
    # Diagonal elements from charge terms
    H_charge_elem = (
        125.174717*n1_i**2 + 125.174717*n2_i**2 + 125.174717*ng1**2 + 125.174717*ng2**2
        + 250.349433*n1_i*ng1 + 250.349433*n2_i*ng2 - 249.650567*n1_i*n2_i - 249.650567*n1_i*ng2
        - 249.650567*n2_i*ng1 - 249.650567*ng1*ng2
    )

    # Off-diagonal elements from Josephson terms
    for delta_n1 in [-1, 0, 1]:
        for delta_n2 in [-1, 0, 1]:
            n1_j = n1_i + delta_n1
            n2_j = n2_i + delta_n2
            if (n1_j, n2_j) in state_indices:
                idx_j = state_indices[(n1_j, n2_j)]
                H_josephson_elem = 0

                # -1.8*cos(Theta1)
                if delta_n1 in [-1, 1] and delta_n2 == 0:
                    H_josephson_elem += -0.9  # Half coefficient due to cosine expansion

                # -1.8*cos(2πΦ1 - Theta2)
                if delta_n1 == 0 and delta_n2 in [-1, 1]:
                    H_josephson_elem += -0.9 * sympy.cos(2*pi*Phi1)  # Adjust coefficient accordingly

                # -18.0*cos(Theta1 + Theta2)
                if delta_n1 == delta_n2 and delta_n1 in [-1, 1]:
                    H_josephson_elem += -9.0  # Half coefficient due to cosine expansion

                # Total matrix element
                H_elem = H_charge_elem if idx_i == idx_j else H_josephson_elem

                # Accumulate the Hamiltonian matrix element
                H_matrix[idx_i, idx_j] += H_elem

# Define subspaces based on parity of total charge
subspace_indices = []
for (n1_val, n2_val) in basis_states:
    parity = (n1_val + n2_val) % 2
    subspace_indices.append(parity)

# Block diagonalize the Hamiltonian
H_tilde, U, U_adjoint = block_diagonalize(
    H_matrix, subspace_indices=subspace_indices, symbols=[]
)


NotImplementedError: Cannot extract diagonal from <class 'pymablock.series.BlockSeries'>